---
- name: Apache Installation auf Debian und Rocky Linux
  hosts: all
  become: true
  vars:
    apache_package:
      Debian: apache2
      Ubuntu: apache2
      RedHat: httpd
      Rocky: httpd
      CentOS: httpd

  tasks:
    - name: Apache installieren (abhängig vom OS)
      package:
        name: "{{ apache_package[ansible_distribution] }}"
        state: present

    - name: Apache Dienst aktivieren und starten
      service:
        name: "{{ apache_package[ansible_distribution] }}"
        state: started
        enabled: yes
